export const MOBILE_TABS = {
  student: [
    {
      id: 'student-home',
      label: 'Dashboard',
      title: 'Home',
      icon: 'home',
      featureIds: ['student-dashboard'],
    },
    {
      id: 'student-learn',
      label: 'Learn',
      title: 'Learning',
      icon: 'book-open-page-variant',
      featureIds: [
        'student-courses',
        'student-my-courses',
        'student-course-detail',
        'student-my-course-content',
      ],
    },
    {
      id: 'student-notifications',
      label: 'Notifications',
      title: 'Notifications',
      icon: 'bell',
      featureIds: ['student-notifications'],
    },
    {
      id: 'student-chat',
      label: 'Chat',
      title: 'Chat',
      icon: 'message-text',
      featureIds: ['student-chat'],
    },
    {
      id: 'student-more',
      label: 'More',
      title: 'Profile',
      icon: 'dots-horizontal-circle',
      featureIds: [
        'student-profile',
        'student-wallet',
        'student-paths',
        'student-leaderboard',
        'student-certificates',
        'student-certificate-quizzes',
      ],
    },
  ],
  teacher: [
    {
      id: 'teacher-home',
      label: 'Dashboard',
      title: 'Home',
      icon: 'home',
      featureIds: ['teacher-dashboard', 'teacher-live-sessions', 'teacher-notifications'],
    },
    {
      id: 'teacher-courses',
      label: 'Courses',
      title: 'Courses',
      icon: 'book-education',
      featureIds: ['teacher-courses'],
    },
    {
      id: 'teacher-notifications',
      label: 'Notifications',
      title: 'Notifications',
      icon: 'bell',
      featureIds: ['teacher-notifications'],
    },
    {
      id: 'teacher-chat',
      label: 'Chat',
      title: 'Inbox',
      icon: 'forum',
      featureIds: ['teacher-chat'],
    },
    {
      id: 'teacher-more',
      label: 'More',
      title: 'Profile',
      icon: 'dots-horizontal-circle',
      featureIds: [
        'teacher-profile',
        'teacher-question-bank',
        'teacher-certificates',
        'teacher-messages',
      ],
    },
  ],
  admin: [
    {
      id: 'admin-dashboard',
      label: 'Dashboard',
      title: 'Dashboard',
      icon: 'chart-bar',
      featureIds: ['admin-stats', 'admin-recent-activity', 'admin-revenue-trend'],
    },
    {
      id: 'admin-catalog',
      label: 'Courses',
      title: 'Courses',
      icon: 'book-open-page-variant',
      featureIds: ['admin-courses', 'admin-categories', 'admin-paths'],
    },
    {
      id: 'admin-notifications',
      label: 'Notifications',
      title: 'Notifications',
      icon: 'bell',
      featureIds: ['admin-notifications'],
    },
    {
      id: 'admin-messages',
      label: 'Messages',
      title: 'Messages',
      icon: 'message-text',
      featureIds: ['admin-messages'],
    },
    {
      id: 'admin-more',
      label: 'More',
      title: 'More',
      icon: 'dots-horizontal-circle',
      featureIds: [
        'admin-certificates',
        'admin-students',
        'admin-teachers',
        'admin-transactions',
        'admin-reports',
      ],
    },
  ],
};
