import { StyleSheet } from 'react-native';

export const portalStyles = StyleSheet.create({
  adminShellPage: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  adminShellTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 25,
    elevation: 12,
    minHeight: 62,
    paddingHorizontal: 12,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#dbe4ef',
    backgroundColor: '#ffffff',
  },
  adminBrandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    maxWidth: '46%',
  },
  adminMenuBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  adminMenuLines: {
    width: 16,
    gap: 3,
  },
  adminMenuLine: {
    width: 16,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#0f2740',
  },
  adminLogo: {
    width: 70,
    height: 44,
  },
  adminLogoWrap: {
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  adminBrandTextWrap: {
    minWidth: 0,
  },
  adminBrandName: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  adminBrandSub: {
    color: '#64748b',
    fontSize: 11,
    marginTop: 1,
  },
  adminTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  adminTopBtn: {
    borderRadius: 9,
    paddingHorizontal: 9,
    paddingVertical: 7,
    backgroundColor: '#dbeafe',
  },
  adminTopBtnText: {
    color: '#1d4ed8',
    fontWeight: '700',
    fontSize: 12,
  },
  adminTopLogoutBtn: {
    borderRadius: 9,
    paddingHorizontal: 9,
    paddingVertical: 7,
    backgroundColor: '#fee2e2',
  },
  adminTopLogoutText: {
    color: '#b91c1c',
    fontWeight: '700',
    fontSize: 12,
  },
  adminShellBody: {
    flex: 1,
    flexDirection: 'row',
  },
  adminSidebar: {
    width: 214,
    backgroundColor: '#0f2740',
  },
  adminMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingBottom: 0,
  },
  adminMenuBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.30)',
  },
  adminDrawerMobile: {
    width: '96%',
    maxWidth: 420,
    maxHeight: '70%',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#dbe4ef',
    backgroundColor: '#ffffff',
    paddingTop: 12,
    paddingBottom: 8,
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -2 },
    elevation: 18,
  },
  adminDrawerScroll: {
    maxHeight: '100%',
  },
  adminSidebarContent: {
    padding: 10,
    gap: 6,
  },
  adminSidebarContentMobile: {
    paddingHorizontal: 14,
    paddingBottom: 12,
    gap: 12,
  },
  adminSidebarUser: {
    color: '#dbeafe',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  adminSidebarUserMobile: {
    color: '#0f172a',
    fontSize: 14,
    marginBottom: 4,
  },
  adminNavItem: {
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  adminNavItemActive: {
    backgroundColor: '#dbeafe',
  },
  adminNavItemText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
  },
  adminNavItemTextActive: {
    color: '#0f2740',
    fontWeight: '700',
  },
  adminSubmenuWrap: {
    marginLeft: 12,
    marginTop: -2,
    marginBottom: 2,
    gap: 4,
  },
  adminSubmenuWrapMobile: {
    marginLeft: 0,
    marginTop: 0,
    marginBottom: 0,
    gap: 8,
  },
  adminSubmenuGroupTitle: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  adminSubmenuGroupTitleMobile: {
    color: '#334155',
    fontSize: 12,
    marginBottom: 0,
    paddingHorizontal: 2,
  },
  adminSubmenuItem: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  adminSubmenuItemMobile: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 12,
  },
  adminSubmenuItemActive: {
    backgroundColor: '#dbeafe',
  },
  adminSubmenuItemActiveMobile: {
    borderColor: '#60a5fa',
    backgroundColor: '#eff6ff',
  },
  adminSubmenuText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '600',
  },
  adminSubmenuTextMobile: {
    color: '#334155',
    fontSize: 12,
  },
  adminSubmenuTextActive: {
    color: '#0f2740',
    fontWeight: '700',
  },
  adminSubmenuTextActiveMobile: {
    color: '#1d4ed8',
  },
  adminContent: {
    flex: 1,
  },
  adminContentInner: {
    padding: 12,
    paddingBottom: 24,
  },
  page: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    marginBottom: 10,
    gap: 6,
  },
  topBtn: {
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
  },
  topBtnText: {
    color: '#0f3b82',
    fontWeight: '700',
  },
  topIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  topInfo: {
    flex: 1,
    minWidth: 0,
  },
  topBarSpacer: {
    flex: 1,
  },
  topLogoWrap: {
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  topLogo: {
    width: 62,
    height: 34,
  },
  themeToggleBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  topName: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 14,
  },
  topRole: {
    color: '#475569',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 1,
  },
  topContextTiny: {
    color: '#94a3b8',
    fontSize: 10,
    marginTop: 1,
  },
  logoutBtn: {
    minWidth: 86,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#fee2e2',
    alignItems: 'center',
  },
  logoutText: {
    color: '#b91c1c',
    fontWeight: '700',
  },
  logoutBtnCompact: {
    minWidth: 72,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#fee2e2',
    alignItems: 'center',
  },
  secondaryTopBtn: {
    minWidth: 66,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
  },
  secondaryTopBtnText: {
    color: '#334155',
    fontWeight: '700',
    fontSize: 11,
  },
  userAvatar: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0d3b66',
  },
  userAvatarText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  mobileSearchWrap: {
    marginBottom: 10,
  },
  tabScroll: {
    maxHeight: 46,
    marginBottom: 8,
  },
  tabRow: {
    gap: 8,
    paddingRight: 20,
  },
  tabPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#cbd5e1',
  },
  tabPillActive: {
    backgroundColor: '#0d3b66',
  },
  tabText: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 12,
  },
  tabTextActive: {
    color: '#ffffff',
  },
  tabBadge: {
    minWidth: 18,
    paddingHorizontal: 5,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: '#b91c1c',
  },
  tabBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  featureScroll: {
    maxHeight: 46,
    marginBottom: 10,
  },
  featureRow: {
    gap: 8,
    paddingRight: 20,
  },
  featurePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
  },
  featurePillActive: {
    backgroundColor: '#0d3b66',
  },
  featureText: {
    color: '#334155',
    fontWeight: '600',
    fontSize: 12,
  },
  featureTextActive: {
    color: '#ffffff',
  },
  toolList: {
    gap: 8,
    marginTop: 8,
  },
  toolItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbe4ef',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  toolItemActive: {
    borderColor: '#0d3b66',
    backgroundColor: '#e6f0fa',
  },
  toolItemText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '600',
  },
  toolItemTextActive: {
    color: '#0d3b66',
    fontWeight: '700',
  },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 10,
  },
  panelTitle: {
    color: '#0f172a',
    fontWeight: '800',
    fontSize: 16,
  },
  endpoint: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 4,
  },
  paramsWrap: {
    marginTop: 10,
    gap: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
    color: '#0f172a',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  secondaryBtn: {
    borderRadius: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: '#dbeafe',
  },
  secondaryBtnText: {
    color: '#1d4ed8',
    fontWeight: '700',
    fontSize: 12,
  },
  financeFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  financeFilterActive: {
    backgroundColor: '#bfdbfe',
  },
  notice: {
    color: '#9a3412',
    marginTop: 8,
    fontSize: 12,
  },
  error: {
    color: '#b91c1c',
    marginTop: 8,
    fontSize: 12,
  },
  summary: {
    color: '#0f766e',
    marginTop: 8,
    fontSize: 12,
    fontWeight: '600',
  },
  dataWrap: {
    flex: 1,
  },
  dataContent: {
    paddingBottom: 24,
    gap: 8,
  },
  loader: {
    marginTop: 16,
  },
  empty: {
    color: '#475569',
    marginTop: 8,
    fontSize: 13,
  },
  adminWrap: {
    gap: 10,
  },
  adminHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  adminHeaderTitle: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '800',
  },
  adminSubTitle: {
    color: '#64748b',
    fontSize: 13,
    marginBottom: 2,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
  },
  statValue: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  statLabel: {
    color: '#64748b',
    marginTop: 6,
    fontSize: 12,
  },
  adminSection: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    gap: 8,
  },
  adminSectionTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  chartWrap: {
    backgroundColor: '#f8fbff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    paddingTop: 4,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  chartCanvas: {
    position: 'relative',
    overflow: 'hidden',
  },
  chartGridLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#dbeafe',
  },
  areaColumn: {
    position: 'absolute',
    width: 8,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
  },
  linePoint: {
    position: 'absolute',
    height: 3,
    width: 3,
    borderRadius: 999,
    backgroundColor: '#2563eb',
  },
  chartLineSegment: {
    position: 'absolute',
    height: 2,
    borderRadius: 2,
    backgroundColor: '#2563eb',
  },
  chartDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#1d4ed8',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  xAxisRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  xAxisLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '600',
  },
  trendFooter: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trendFooterLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  trendFooterValue: {
    color: '#1e40af',
    fontSize: 13,
    fontWeight: '800',
  },
  insightRow: {
    backgroundColor: '#eff6ff',
    borderRadius: 10,
    padding: 10,
  },
  insightTitle: {
    color: '#1e3a8a',
    fontSize: 12,
    fontWeight: '800',
  },
  insightBody: {
    color: '#334155',
    fontSize: 12,
    marginTop: 2,
  },
  listItem: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 8,
  },
  listCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#ffffff',
    gap: 2,
  },
  listItemContent: {
    gap: 2,
  },
  listItemTitle: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '600',
  },
  listItemMeta: {
    color: '#64748b',
    fontSize: 12,
  },
  financeTransactionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  financeTypePill: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
  },
  financeTypePillEnrollment: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  financeTypePillRefund: {
    backgroundColor: '#f1f5f9',
    borderColor: '#cbd5e1',
  },
  financeTypePillText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  financeTypePillTextEnrollment: {
    color: '#1d4ed8',
  },
  financeTypePillTextRefund: {
    color: '#334155',
  },
  financeTransactionStatsRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  financeTransactionStatCell: {
    minWidth: 90,
    flexGrow: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  financeTransactionStatLabel: {
    fontSize: 10,
    fontWeight: '600',
  },
  financeTransactionStatValue: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  notificationMetaRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  notificationMetaText: {
    fontSize: 11,
    color: '#64748b',
  },
  notificationLinkText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
  },
  notificationActionBtn: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: '#dbeafe',
  },
  notificationActionText: {
    color: '#1d4ed8',
    fontSize: 11,
    fontWeight: '700',
  },
  listItemValue: {
    color: '#1e3a8a',
    fontWeight: '700',
    fontSize: 13,
    marginTop: 4,
  },
  activityType: {
    alignSelf: 'flex-start',
    color: '#1e40af',
    backgroundColor: '#dbeafe',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontWeight: '700',
    fontSize: 10,
    overflow: 'hidden',
    marginBottom: 2,
  },
  threadItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#ffffff',
  },
  threadItemActive: {
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
  },
  threadTeacher: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 13,
  },
  threadMeta: {
    color: '#64748b',
    fontSize: 11,
    marginTop: 2,
  },
  chatBubble: {
    maxWidth: '90%',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  chatBubbleAdmin: {
    alignSelf: 'flex-end',
    backgroundColor: '#dbeafe',
  },
  chatBubbleTeacher: {
    alignSelf: 'flex-start',
    backgroundColor: '#f1f5f9',
  },
  chatText: {
    color: '#0f172a',
    fontSize: 12,
  },
  chatComposerRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: '#0f172a',
  },
  chatSendBtn: {
    borderRadius: 10,
    backgroundColor: '#2563eb',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chatSendText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  menuOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingBottom: 0,
  },
  menuOverlayTouch: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.30)',
  },
  menuDrawer: {
    width: '96%',
    maxWidth: 420,
    maxHeight: '70%',
    borderWidth: 1,
    borderColor: '#dbe4ef',
    borderRadius: 22,
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -2 },
    elevation: 18,
  },
  menuDrawerScroll: {
    maxHeight: '100%',
  },
  menuDrawerContent: {
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 14,
  },
  dialogOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 45,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  dialogOverlayTouch: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
  },
  dialogCard: {
    width: '96%',
    maxWidth: 430,
    maxHeight: '78%',
    borderWidth: 1,
    borderColor: '#dbe4ef',
    borderRadius: 22,
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -2 },
    elevation: 20,
  },
  dialogCardCompact: {
    maxHeight: undefined,
  },
  dialogScroll: {
    maxHeight: '100%',
  },
  dialogContent: {
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 14,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#cbd5e1',
  },
  modalSheetHeader: {
    gap: 2,
  },
  modalSheetTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  modalSheetSubtitle: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '500',
  },
  menuSection: {
    gap: 8,
  },
  menuSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuSectionTitle: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '800',
  },
  menuSectionBadge: {
    minWidth: 18,
    paddingHorizontal: 5,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: '#b91c1c',
  },
  menuSectionBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  menuItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  menuItemActive: {
    borderColor: '#60a5fa',
    backgroundColor: '#eff6ff',
  },
  menuItemText: {
    color: '#334155',
    fontWeight: '600',
    fontSize: 13,
  },
  menuItemTextActive: {
    color: '#1d4ed8',
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 0,
    borderWidth: 1,
    borderColor: '#dbe4ef',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 8,
    paddingHorizontal: 6,
    shadowColor: '#0f172a',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -2 },
    elevation: 10,
  },
  bottomNavItem: {
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  bottomNavIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  bottomNavLabel: {
    color: '#64748b',
    fontWeight: '700',
    fontSize: 11,
  },
  bottomNavLabelActive: {
    color: '#0d3b66',
  },
  bottomNavBadge: {
    minWidth: 18,
    paddingHorizontal: 4,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: '#b91c1c',
  },
  bottomNavBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
});
