import { StyleSheet } from 'react-native';

export const portalStyles = StyleSheet.create({
  adminShellPage: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  adminShellTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 25,
    elevation: 12,
    minHeight: 62,
    paddingHorizontal: 12,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#dbe4ef',
    backgroundColor: '#ffffff',
  },
  adminBrandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    maxWidth: '46%',
  },
  adminMenuBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  adminMenuLines: {
    width: 16,
    gap: 3,
  },
  adminMenuLine: {
    width: 16,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#0f2740',
  },
  adminLogo: {
    width: 58,
    height: 44,
    tintColor: '#003153',
  },
  adminBrandTextWrap: {
    minWidth: 0,
  },
  adminBrandName: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  adminBrandSub: {
    color: '#64748b',
    fontSize: 11,
    marginTop: 1,
  },
  adminTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  adminTopBtn: {
    borderRadius: 9,
    paddingHorizontal: 9,
    paddingVertical: 7,
    backgroundColor: '#dbeafe',
  },
  adminTopBtnText: {
    color: '#1d4ed8',
    fontWeight: '700',
    fontSize: 12,
  },
  adminTopLogoutBtn: {
    borderRadius: 9,
    paddingHorizontal: 9,
    paddingVertical: 7,
    backgroundColor: '#fee2e2',
  },
  adminTopLogoutText: {
    color: '#b91c1c',
    fontWeight: '700',
    fontSize: 12,
  },
  adminShellBody: {
    flex: 1,
    flexDirection: 'row',
  },
  adminSidebar: {
    width: 214,
    backgroundColor: '#0f2740',
  },
  adminMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  adminMenuBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.38)',
  },
  adminDrawerMobile: {
    width: 250,
    height: '100%',
    backgroundColor: '#0f2740',
    borderRightWidth: 1,
    borderRightColor: '#1e3a5f',
    paddingTop: 12,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 3, height: 0 },
    elevation: 16,
  },
  adminDrawerScroll: {
    flex: 1,
  },
  adminSidebarContent: {
    padding: 10,
    gap: 6,
  },
  adminSidebarUser: {
    color: '#dbeafe',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  adminNavItem: {
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  adminNavItemActive: {
    backgroundColor: '#dbeafe',
  },
  adminNavItemText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
  },
  adminNavItemTextActive: {
    color: '#0f2740',
    fontWeight: '700',
  },
  adminSubmenuWrap: {
    marginLeft: 12,
    marginTop: -2,
    marginBottom: 2,
    gap: 4,
  },
  adminSubmenuItem: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  adminSubmenuItemActive: {
    backgroundColor: '#dbeafe',
  },
  adminSubmenuText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '600',
  },
  adminSubmenuTextActive: {
    color: '#0f2740',
    fontWeight: '700',
  },
  adminContent: {
    flex: 1,
  },
  adminContentInner: {
    padding: 12,
    paddingBottom: 24,
  },
  page: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    marginBottom: 10,
    gap: 8,
  },
  topBtn: {
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
  },
  topBtnText: {
    color: '#0f3b82',
    fontWeight: '700',
  },
  topInfo: {
    flex: 1,
    minWidth: 0,
  },
  topName: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 14,
  },
  topRole: {
    color: '#475569',
    fontSize: 11,
    marginTop: 1,
  },
  logoutBtn: {
    minWidth: 86,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#fee2e2',
    alignItems: 'center',
  },
  logoutText: {
    color: '#b91c1c',
    fontWeight: '700',
  },
  featureScroll: {
    maxHeight: 46,
    marginBottom: 10,
  },
  featureRow: {
    gap: 8,
    paddingRight: 20,
  },
  featurePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
  },
  featurePillActive: {
    backgroundColor: '#0d3b66',
  },
  featureText: {
    color: '#334155',
    fontWeight: '600',
    fontSize: 12,
  },
  featureTextActive: {
    color: '#ffffff',
  },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 10,
  },
  panelTitle: {
    color: '#0f172a',
    fontWeight: '800',
    fontSize: 16,
  },
  endpoint: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 4,
  },
  paramsWrap: {
    marginTop: 10,
    gap: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
    color: '#0f172a',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  loadBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#0d3b66',
  },
  loadBtnDisabled: {
    opacity: 0.6,
  },
  loadText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  secondaryBtn: {
    borderRadius: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: '#dbeafe',
  },
  secondaryBtnText: {
    color: '#1d4ed8',
    fontWeight: '700',
    fontSize: 12,
  },
  notice: {
    color: '#9a3412',
    marginTop: 8,
    fontSize: 12,
  },
  error: {
    color: '#b91c1c',
    marginTop: 8,
    fontSize: 12,
  },
  summary: {
    color: '#0f766e',
    marginTop: 8,
    fontSize: 12,
    fontWeight: '600',
  },
  dataWrap: {
    flex: 1,
  },
  dataContent: {
    paddingBottom: 24,
    gap: 8,
  },
  loader: {
    marginTop: 16,
  },
  empty: {
    color: '#475569',
    marginTop: 8,
    fontSize: 13,
  },
  adminWrap: {
    gap: 10,
  },
  adminHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  adminHeaderTitle: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '800',
  },
  adminRefreshBtn: {
    backgroundColor: '#dbeafe',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  adminRefreshText: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '700',
  },
  adminSubTitle: {
    color: '#64748b',
    fontSize: 13,
    marginBottom: 2,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
  },
  statValue: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  statLabel: {
    color: '#64748b',
    marginTop: 6,
    fontSize: 12,
  },
  adminSection: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    gap: 8,
  },
  adminSectionTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  chartWrap: {
    backgroundColor: '#f8fbff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    paddingTop: 4,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  chartCanvas: {
    position: 'relative',
    overflow: 'hidden',
  },
  chartGridLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#dbeafe',
  },
  areaColumn: {
    position: 'absolute',
    width: 8,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
  },
  linePoint: {
    position: 'absolute',
    height: 3,
    width: 3,
    borderRadius: 999,
    backgroundColor: '#2563eb',
  },
  chartDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#1d4ed8',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  xAxisRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  xAxisLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '600',
  },
  trendFooter: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trendFooterLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  trendFooterValue: {
    color: '#1e40af',
    fontSize: 13,
    fontWeight: '800',
  },
  insightRow: {
    backgroundColor: '#eff6ff',
    borderRadius: 10,
    padding: 10,
  },
  insightTitle: {
    color: '#1e3a8a',
    fontSize: 12,
    fontWeight: '800',
  },
  insightBody: {
    color: '#334155',
    fontSize: 12,
    marginTop: 2,
  },
  listItem: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 8,
  },
  listCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#ffffff',
    gap: 2,
  },
  listItemContent: {
    gap: 2,
  },
  listItemTitle: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '600',
  },
  listItemMeta: {
    color: '#64748b',
    fontSize: 12,
  },
  listItemValue: {
    color: '#1e3a8a',
    fontWeight: '700',
    fontSize: 13,
    marginTop: 4,
  },
  activityType: {
    alignSelf: 'flex-start',
    color: '#1e40af',
    backgroundColor: '#dbeafe',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontWeight: '700',
    fontSize: 10,
    overflow: 'hidden',
    marginBottom: 2,
  },
  threadItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#ffffff',
  },
  threadItemActive: {
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
  },
  threadTeacher: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 13,
  },
  threadMeta: {
    color: '#64748b',
    fontSize: 11,
    marginTop: 2,
  },
  chatBubble: {
    maxWidth: '90%',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  chatBubbleAdmin: {
    alignSelf: 'flex-end',
    backgroundColor: '#dbeafe',
  },
  chatBubbleTeacher: {
    alignSelf: 'flex-start',
    backgroundColor: '#f1f5f9',
  },
  chatText: {
    color: '#0f172a',
    fontSize: 12,
  },
  chatComposerRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: '#0f172a',
  },
  chatSendBtn: {
    borderRadius: 10,
    backgroundColor: '#2563eb',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chatSendText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
});
